---
title: "Progetto"
author: "Jacopo Corubolo"
output:
  ioslides_presentation:
    css: ../style.css
    incremental: yes
  beamer_presentation:
    incremental: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, echo = TRUE, message=FALSE, warning = FALSE, fig.align='center')
```

# Campionato di SerieA  2009/2010 - 2018/2019

```{r, include=FALSE}
library(shiny)
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)




history = read_csv("history.csv")
Nteam = read_csv("Team.csv")
      
      historyA = separate(history, Date, into = c("Y", "Mese", "Giorno"),  sep = "-", convert = TRUE)
      
      historyAb = separate(historyA, Y, into = c("R", "Anno"), sep = 2, convert = TRUE) %>%
        select(Anno, Mese, Giorno, HomeTeam, AwayTeam, FTHG, FTAG)
      
      
      historyB = historyAb %>%
         mutate(Y1 = ifelse(Mese > 8, Anno, ifelse(Mese < 8, Anno - 1, ifelse(Giorno > 5, Anno, Anno - 1))),
                Y2 = ifelse(Mese > 8, Anno + 1, ifelse(Mese < 8, Anno, ifelse(Giorno > 5, Anno + 1, Anno))))
      
      historyC = unite(historyB, Y1, Y2, col = "Stagione", sep = "/")
      
      historyD = historyB %>%
        filter(Y1 > 10)
      
      SerieATot = unite(historyD, Y1, Y2, col = "Stagione", sep = "/")
      
      dfHtot = SerieATot %>% 
         mutate(outcome = ifelse(FTHG > FTAG, "H", 
                                 ifelse(FTHG < FTAG, "A", "D"))) %>% 
         count(HomeTeam, outcome) %>% 
         spread(key = outcome, value = n) %>% 
         rename(team = HomeTeam, winsHome = H, 
                drawsHome = D, 
                losesHome = A) %>% 
         mutate(winsHome = ifelse(is.na(winsHome), 0, winsHome), 
                drawsHome = ifelse(is.na(drawsHome), 0, drawsHome), 
                losesHome = ifelse(is.na(losesHome), 
                                   0, 
                                   losesHome)) %>% 
         select(team, winsHome, drawsHome, losesHome) %>% 
         mutate(pointsHome = 3 * winsHome + drawsHome) %>% 
         arrange(team)
      
      dfAtot = SerieATot %>%
         mutate(outcome = ifelse(FTHG > FTAG, "H", 
                                 ifelse(FTHG < FTAG, "A", "D"))) %>% 
         count(AwayTeam, outcome) %>% 
         spread(key = outcome, value = n) %>% 
         rename(team = AwayTeam, winsAway = A, 
                drawsAway = D, 
                losesAway = H) %>% 
         mutate(winsAway = ifelse(is.na(winsAway), 0, winsAway), 
                drawsAway = ifelse(is.na(drawsAway), 0, drawsAway), 
                losesAway = ifelse(is.na(losesAway), 0, losesAway)) %>% 
         mutate(pointsAway = 3*winsAway + drawsAway) %>% 
         arrange(team)
      
      
      ratingTot = inner_join(dfHtot, dfAtot) %>%
         mutate(wins = winsHome + winsAway, 
                draws = drawsHome + drawsAway,
                loses = losesHome + losesAway, 
                points = pointsHome + pointsAway,
                matches = wins + loses + draws,
                pointsPerMatch = points / matches) %>% 
         select(team, matches, points, pointsPerMatch, 
                wins, draws, loses) %>% 
         arrange(-matches)  %>%
         filter(row_number() <= 15)
      
      Classifica = ratingTot %>%
        left_join(Nteam, c("team" = "Team"))
      
      

      TroferiPerPunti = ggplot(data = Classifica, aes(x = Name, color = Name)) +
              geom_point(mapping = aes(y = points, size = Trofei)) +
              scale_size(range = c(5, 30)) +
          theme_classic(base_size = 10) + 
          labs(x = "Team", y = "Points") +
          theme(legend.position = "none")
      
      SpesePerPunti = ggplot(data = Classifica, aes(x = Name, color = Name)) +
              geom_point(mapping = aes(y = points, size = Spese)) +
              scale_size(range = c(5, 30)) +
          theme_classic(base_size = 10) + 
          labs(x = "Team", y = "Points") +
          theme(legend.position = "none")
```

## Investimenti

```{r}
SpesePerPunti
```

## Trofei

```{r}
TroferiPerPunti
```

## Atalanta

Successo Atalanta

```{r, include=FALSE}
library(dplyr)

historyAata = separate(history, Date, into = c("Anno", "Mese", "Giorno"), sep = "-", convert = TRUE)
      
      
      historyBata = historyAata %>%
         mutate(Y1 = ifelse(Mese > 8, Anno, ifelse(Mese < 8, Anno - 1, ifelse(Giorno > 5, Anno, Anno - 1))),
                Y2 = ifelse(Mese > 8, Anno + 1, ifelse(Mese < 8, Anno, ifelse(Giorno > 5, Anno + 1, Anno))))
      
      historyCata = unite(historyBata, Y1, Y2, col = "Stagione", sep = "/")

SerieAata = historyCata %>%
    group_by(Stagione)
      
      dfHata = SerieAata %>% 
         mutate(outcome = ifelse(FTHG > FTAG, "H", ifelse(FTHG < FTAG, "A", "D"))) %>% 
         count(HomeTeam, outcome) %>% 
         spread(key = outcome, value = n) %>% 
         rename(team = HomeTeam, winsHome = H, 
                drawsHome = D, 
                losesHome = A) %>% 
         mutate(winsHome = ifelse(is.na(winsHome), 0, winsHome), 
                drawsHome = ifelse(is.na(drawsHome), 0, drawsHome), 
                losesHome = ifelse(is.na(losesHome), 0, losesHome)) %>% 
         select(team, winsHome, drawsHome, losesHome) %>% 
         mutate(pointsHome = 3 * winsHome + drawsHome) %>% 
         arrange(team)
      
      dfAata = SerieAata %>%
         mutate(outcome = ifelse(FTHG > FTAG, "H", ifelse(FTHG < FTAG, "A", "D"))) %>% 
         count(AwayTeam, outcome) %>% 
         spread(key = outcome, value = n) %>% 
         rename(team = AwayTeam, winsAway = A, 
                drawsAway = D, 
                losesAway = H) %>% 
         mutate(winsAway = ifelse(is.na(winsAway), 0, winsAway), 
                drawsAway = ifelse(is.na(drawsAway), 0, drawsAway), 
                losesAway = ifelse(is.na(losesAway), 0, losesAway)) %>% 
         mutate(pointsAway = 3*winsAway + drawsAway) %>% 
         arrange(team)
      
      GHSata = SerieAata %>% 
         count(HomeTeam, FTHG) %>% 
         mutate(Num = FTHG * n) %>%
         group_by(HomeTeam, Stagione) %>%
         summarise(GoalHomeS = sum(Num))
      
      GASata = SerieAata %>% 
         count(AwayTeam, FTAG) %>% 
         mutate(Num = FTAG * n) %>%
         group_by(AwayTeam, Stagione) %>%
         summarise(GoalAwayS = sum(Num))
      
      
      ratingGSata = GHSata %>%
         left_join(GASata, c("HomeTeam" = "AwayTeam", "Stagione" = "Stagione")) %>%
         mutate(TotGoalS = GoalHomeS + GoalAwayS)
      
      
      GHCata = SerieAata %>% 
         count(HomeTeam, FTAG) %>% 
         mutate(Num = FTAG * n) %>%
         group_by(HomeTeam, Stagione) %>%
         summarise(GoalHomeC = sum(Num))
      
      GACata = SerieAata %>% 
         count(AwayTeam, FTHG) %>% 
         mutate(Num = FTHG * n) %>%
         group_by(AwayTeam, Stagione) %>%
         summarise(GoalAwayC = sum(Num))
      
      
      ratingGCata = GHCata %>%
         left_join(GACata, c("HomeTeam" = "AwayTeam", "Stagione" = "Stagione")) %>%
         mutate(TotGoalC = GoalHomeC + GoalAwayC)
      
      ratingGata = ratingGSata %>%
         left_join(ratingGCata, c("HomeTeam" = "HomeTeam", "Stagione" = "Stagione"))
      
      ratingAta = inner_join(dfHata, dfAata) %>% 
         mutate(wins = winsHome + winsAway, 
                draws = drawsHome + drawsAway,
                loses = losesHome + losesAway, 
                points = pointsHome + pointsAway,
                matches = wins + loses + draws,
                pointsPerMatch = points / matches) %>% 
         select(team, matches, points, pointsPerMatch,everything()) %>% 
         arrange(-pointsPerMatch)
      
      
      TotRatingAta = ratingAta %>%
         left_join(ratingGata, c("team" = "HomeTeam", "Stagione" = "Stagione")) %>%
         mutate(agsHome = GoalHomeS / (winsHome + drawsHome + losesHome),
                agsAway = GoalAwayS / (winsAway + drawsAway + losesAway),
                ags = TotGoalS / (wins + draws + loses),
                agcHome = GoalHomeC / (winsHome + drawsHome + losesHome),
                agcAway = GoalAwayC / (winsAway + drawsAway + losesAway),
                agc = TotGoalC / (wins + draws + loses),
                DR = TotGoalS - TotGoalC ) %>%
         arrange(team, Stagione) %>%
        group_by(team) %>%
        filter(team == "Atalanta") %>%
        mutate(n = row_number())
      
      ATA = TotRatingAta %>%
       filter(n >= 16) %>%
        mutate(k = n - 15) %>%
        mutate(mister = ifelse(k == 1,"Colantuno-Reja", ifelse(k == 2, "Reja", "Gasperini")))
      
      
        

      PuntiAtalanta = ggplot(data = ATA, aes(x = Stagione, fill = mister)) +
         geom_col(mapping = aes(y = points)) +
         theme_classic() + 
         labs(x = "Season", y = "Points") +
         theme(
             legend.title = element_text(face = "bold", size = 8),
             legend.text = element_text(size = 8),
             legend.position = "bottom"
    )

GolRealizzatiAta = ggplot(data = ATA, aes(x = Stagione,y = points, size = TotGoalS, color = mister)) +
  geom_point() +
  scale_size(range = c(5, 30)) +
    theme_classic() + 
    labs(x = "Season", y = "Points") +
    theme(legend.position = "none")

GolSubitiAta = ggplot(data = ATA, aes(x = Stagione,y = points, size = TotGoalC, color = mister)) +
  geom_point() +
  scale_size(range = c(5, 30)) +
    theme_classic() + 
    labs(x = "Season", y = "Points") +
    theme(legend.position = "none")


      GHSata2 = SerieAata %>% 
         count(HomeTeam, FTHG) %>%
         filter(HomeTeam == "Atalanta",
                FTHG >= 3) %>% 
         group_by(Stagione) %>%
         summarise(N3H = sum(n)) %>%
        mutate(nh = row_number())
      
      GASata2 = SerieAata %>% 
         count(AwayTeam, FTAG) %>% 
         filter(AwayTeam == "Atalanta", FTAG >= 3)%>%
         group_by(Stagione) %>%
         summarise(N3A = sum(n)) %>%
         mutate(na = row_number())
      
      ratingGSata2 = GHSata2 %>%
         left_join(GASata2, c("Stagione" = "Stagione")) %>%
         mutate(N3H = ifelse(is.na(N3H), 0, N3H),
                N3A = ifelse(is.na(N3A), 0, N3A),
                na = nh,
                n = nh,
                N3 = N3H + N3A)

      
      ATA2 = ratingGSata2 %>%
        filter(n >= 15) %>%
        mutate(k = n - 14) %>%
        mutate(mister = ifelse(k == 1, "Colantuno-Reja", ifelse(k == 2, "Reja", "Gasperini"))) %>%
        select(Stagione, N3, mister)
      
Partite3G = ggplot(data = ATA2, aes(x = Stagione, y = N3, fill = mister)) +
  geom_col() +
    theme_classic() + 
    labs(x = "Season", y = "Matches 3 goals") +
    theme(legend.position = "none")
      
```

```{r}
PuntiAtalanta
```

```{r}
GolRealizzatiAta
```

```{r}
GolSubitiAta
```

```{r}
Partite3G
```

```{r, include=FALSE}
CPS = function(season){

  
  SerieAcps = historyC %>%
         filter(Stagione == season)
      
      dfHcps = SerieAcps %>% 
         mutate(outcome = ifelse(FTHG > FTAG, "H", ifelse(FTHG < FTAG, "A", "D"))) %>% 
         count(HomeTeam, outcome) %>% 
         spread(key = outcome, value = n) %>% 
         rename(team = HomeTeam, winsHome = H, 
                drawsHome = D, 
                losesHome = A) %>% 
         mutate(winsHome = ifelse(is.na(winsHome), 0, winsHome), 
                drawsHome = ifelse(is.na(drawsHome), 0, drawsHome), 
                losesHome = ifelse(is.na(losesHome), 0, losesHome)) %>% 
         select(team, winsHome, drawsHome, losesHome) %>% 
         mutate(pointsHome = 3 * winsHome + drawsHome) %>% 
         arrange(team)
      
      dfAcps = SerieAcps %>%
         mutate(outcome = ifelse(FTHG > FTAG, "H", ifelse(FTHG < FTAG, "A", "D"))) %>% 
         count(AwayTeam, outcome) %>% 
         spread(key = outcome, value = n) %>% 
         rename(team = AwayTeam, winsAway = A, 
                drawsAway = D, 
                losesAway = H) %>% 
         mutate(winsAway = ifelse(is.na(winsAway), 0, winsAway), 
                drawsAway = ifelse(is.na(drawsAway), 0, drawsAway), 
                losesAway = ifelse(is.na(losesAway), 0, losesAway)) %>% 
         mutate(pointsAway = 3*winsAway + drawsAway) %>% 
         arrange(team)
      
      GHScps = SerieAcps %>% 
         count(HomeTeam, FTHG) %>% 
         mutate(Num = FTHG * n) %>%
         group_by(HomeTeam) %>%
         summarise(GoalHomeS = sum(Num))
      
      GAScps = SerieAcps %>% 
         count(AwayTeam, FTAG) %>% 
         mutate(Num = FTAG * n) %>%
         group_by(AwayTeam) %>%
         summarise(GoalAwayS = sum(Num))
      
      
      ratingGScps = GHScps %>%
         left_join(GAScps, c("HomeTeam" = "AwayTeam")) %>%
         mutate(TotGoalS = GoalHomeS + GoalAwayS)
      
      
      GHCcps = SerieAcps %>% 
         count(HomeTeam, FTAG) %>% 
         mutate(Num = FTAG * n) %>%
         group_by(HomeTeam) %>%
         summarise(GoalHomeC = sum(Num))
      
      GACcps = SerieAcps %>% 
         count(AwayTeam, FTHG) %>% 
         mutate(Num = FTHG * n) %>%
         group_by(AwayTeam) %>%
         summarise(GoalAwayC = sum(Num))
      
      
      ratingGCcps = GHCcps %>%
         left_join(GACcps, c("HomeTeam" = "AwayTeam")) %>%
         mutate(TotGoalC = GoalHomeC + GoalAwayC)
      
      ratingGcps = ratingGScps %>%
         left_join(ratingGCcps, c("HomeTeam" = "HomeTeam"))
      
      ratingcps = inner_join(dfHcps, dfAcps) %>% 
         mutate(wins = winsHome + winsAway, 
                draws = drawsHome + drawsAway,
                loses = losesHome + losesAway, 
                points = pointsHome + pointsAway,
                matches = wins + loses + draws,
                pointsPerMatch = points / matches) %>% 
         select(team, matches, points, pointsPerMatch, everything()) %>% 
         arrange(-pointsPerMatch)
      
      
      ratingcps %>%
         left_join(ratingGcps, c("team" = "HomeTeam")) %>%
         left_join(Nteam, c("team" = "Team")) %>%
         mutate(agsHome = GoalHomeS / (winsHome + drawsHome + losesHome),
                agsAway = GoalAwayS / (winsAway + drawsAway + losesAway),
                ags = TotGoalS / (wins + draws + loses),
                agcHome = GoalHomeC / (winsHome + drawsHome + losesHome),
                agcAway = GoalAwayC / (winsAway + drawsAway + losesAway),
                agc = TotGoalC / (wins + draws + loses),
                DR = TotGoalS - TotGoalC ) %>%
         arrange(-points, ifelse(DR < 0, -DR, DR)) %>%
         mutate(round = row_number(),
                Stagione = season,
                position = ifelse(round == 1, "Winner", ifelse(round > 17, "Relegated", "Saved")))
}
```

```{r,include=FALSE}
c1011 = CPS("10/11") 

c1112 = CPS("11/12") 

c1213 = CPS("12/13") 

c1314 = CPS("13/14") 

c1415 = CPS("14/15") 

c1516 = CPS("15/16") 

c1617 = CPS("16/17") 

c1718 = CPS("17/18") 

c1819 = CPS("18/19") 

c1920 = CPS("19/20") 


ClassTotale = union_all(c1011, 
                        union_all(c1112, 
                            union_all(c1213, 
                                union_all(c1314,
                                    union_all(c1415,
                                        union_all(c1516,
                                            union_all(c1617,
                                                union_all(c1718, 
                                                    union_all(c1819, c1920)))))))))

Class18 = ClassTotale %>%
            filter(round == 19 | round == 18 | round == 17)

G18 = function(valore){
  
  ggplot(data = Class18, aes_string(x = "Stagione", y = "points", color = "round", size = valore)) +
    geom_point() +
    scale_size(range = c(3, 18)) +
    theme_classic() + 
    labs(x = "Season", y = "Points") +
    theme(legend.position = "none")
  
}

puntiDR18 = G18("DR")

GolRealizzati18 = G18("TotGoalS")

GolSubiti18 = G18("TotGoalC")

Class1 = ClassTotale %>%
            filter(round == 1 | round == 2 | round == 3)

G1 = function(valore){
  
  ggplot(data = Class1, aes_string(x = "Stagione", y = "points", color = "round", size = valore)) +
    geom_point() +
    scale_size(range = c(3, 18)) +
    theme_classic() + 
    labs(x = "Season", y = "Points") +
    theme(legend.position = "none")
  
}

puntiDR1 = G1("DR")

GolRealizzati1 = G1("TotGoalS")

GolSubiti1 = G1("TotGoalC")
```

## Scudetto

```{r}
puntiDR1
```

```{r}
GolRealizzati1
```

```{r}
GolSubiti1
```

## Retrtocessione

```{r}
puntiDR18
```

```{r}
GolRealizzati18
```

```{r}
GolSubiti18
```